channels:
- defaults
dependencies:
- python=3.6.8
- pip=20.2
- pip:
  - azureml-contrib-dataset==1.18.0
  - azureml-dataset-runtime==1.18.0
  - azureml-designer-core[image]==0.0.54
  - azureml-designer-cv-modules==0.0.23
  - fire==0.3.0
name: project_environment